### ISSUE TITLE
@Loggable not printing the logs

### ISSUE THREAD

**Issue by praveennsubu** [jcabi/jcabi-aspects#106]
Hey, for some reason @Loggable is not printing out the logs for me. I've been at it for ever now, but can't seem to figure it out. I've added the dependencies and also the jcabi-maven-plugin. I'm using slf4j with log4j and all the other logs that I've used in my spring-mvc application are working. Can you help me sort this out please? Do I have to set up any additional AOP configuration in my project? Do let me know if you'd require more information.

**Comment by dannybaby** [comment]
@praveennsubu Hi, I think I have got the similar problem as yours ,can you help me fix it?
https://github.com/jcabi/jcabi-aspects/issues/142

**Comment by kumarvijaypt** [comment]
@praveennsubu Hi, Can you please let me know what finally made @Loggable to log on file\console.  I think the issue that I am facing is also similar. Reorted it https://github.com/jcabi/jcabi-aspects/issues/179

Thanks for your help in advance

**Comment by praveennsubu** [comment]
@kumarvijaypt Hey.. I never got the chance to look into the matter after that. But it seems the comment above yours has a possible solution. Do let me know if it eventually works for you though. Good luck! Cheers!

**Comment by kumarvijaypt** [comment]
Managed to fix my POM. It works now!.

  <dependencies>
     <dependency>
      <groupId>com.jcabi</groupId>
      <artifactId>jcabi-aspects</artifactId>
      <version>0.22</version>
    </dependency>
    <dependency>
      <groupId>org.aspectj</groupId>
      <artifactId>aspectjrt</artifactId>
      <version>1.5.3</version>
    </dependency>
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-log4j12</artifactId>
        <version>1.7.5</version>
    </dependency>
  </dependencies>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>com.jcabi</groupId>
          <artifactId>jcabi-maven-plugin</artifactId>
          <version>0.9.3</version>
         <configuration>
            <source>1.6</source>
            <target>1.6</target>
         </configuration>
          <executions>
            <execution>
              <goals>
                <goal>ajc</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>com.jcabi</groupId>
        <artifactId>jcabi-maven-plugin</artifactId>
        <version>0.9.3</version>
        <executions>
          <execution>
            <goals>
              <goal>ajc</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.3</version>
        <configuration>
          <source>1.6</source>
          <target>1.6</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
