### ISSUE TITLE
ImmutableTest.java:77-82: Assignment is not intersected, that's...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aspects#118]
Puzzle `104-259d589d` in `src/test/java/com/jcabi/aspects/ImmutableTest.java:77-82` has to be resolved: Assignment is not intersected, that's why this test doesn't work. We simply don't catch the moment when an object is assigned to the private filed of another object. That's why we can't tell when such a mutable class is being used. I think we should introduce a new AspectJ join point in ImmutabilityChecker, which will catch assignments.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by darkled** [comment]
@dmarkov would you mind to close the issue, please, if you don't have any further points here?

**Comment by yegor256** [comment]
@darkled did you remove the puzzle from the source code?

**Comment by darkled** [comment]
@yegor256 yes, sure

**Comment by dmarkov** [comment]
Closing..

**Comment by dmarkov** [comment]
@darkled Thanks for your contribution, **30 mins** was added to your account, payment ID is `49979004`

+30 added to your rating, current score is: [+75](http://www.netbout.com/b/35091?open=rating)
