### ISSUE TITLE
Mnemos.java:289-290: Add handling of int, long,...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aspects#121]
Puzzle `109-bb540c79` in `src/main/java/com/jcabi/aspects/aj/Mnemos.java:289-290` has to be resolved: Add handling of int, long, float, double, char and boolean arrays.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@jenya you're holding this ticket for 12 days already. If it's not finished (and closed) in the next 40 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; do not forget to remove the TODO puzzle from the source code; added -30 to your rating, now it is equal to [-255](http://www.netbout.com/b/35092?open=rating)

**Comment by dmarkov** [comment]
@jenya it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

-60 to your rating, your total score is [-495](http://www.netbout.com/b/35092?open=rating)

**Comment by dmarkov** [comment]
@oruam85 please proceed, it's yours

**Comment by oruam85** [comment]
@dmarkov the PR is https://github.com/jcabi/jcabi-aspects/pull/129

**Comment by oruam85** [comment]
@dmarkov the PR was merged. Please close this bug

**Comment by oruam85** [comment]
@dmarkov the PR was merged. Please close this bug

**Comment by oruam85** [comment]
@dmarkov the PR was merged. Please close this bug

**Comment by dmarkov** [comment]
It's closed now

**Comment by dmarkov** [comment]
@oruam85 I just added **30 mins** to your account, many thanks for your contribution..... +30 added to your rating, at the moment it is: +180
