### ISSUE TITLE
Different results of local and CI qulice invocation

### ISSUE THREAD

**Issue by darkled** [jcabi/jcabi-aspects#122]
Running locally `mvn clean install -Pqulice` leads to 450+ lines in the build log looking like
````
...
[ERROR] \src\test\java\com\jcabi\aspects\UnitedThrowTest.java[118]: Lines in file should end with Unix-like end of line (RegexpMultilineCheck)
[ERROR] \src\test\java\com\jcabi\aspects\UnitedThrowTest.java[129]: Lines in file should end with Unix-like end of line (RegexpMultilineCheck)
[ERROR] \src\test\java\com\jcabi\aspects\UnitedThrowTest.java[137]: Lines in file should end with Unix-like end of line (RegexpMultilineCheck)
[ERROR] \src\test\java\com\jcabi\aspects\UnitedThrowTest.java[148]: Lines in file should end with Unix-like end of line (RegexpMultilineCheck)
[ERROR] \src\test\resources\log4j.properties[27]: Lines in file should end with Unix-like end of line (RegexpMultilineCheck)
[ERROR] \src\test\resources\log4j.properties[32]: Lines in file should end with Unix-like end of line (RegexpMultilineCheck)
[INFO] Read our quality policy: http://www.qulice.com/quality.html
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
...
```
It differs from the actual result [here](https://travis-ci.org/jcabi/jcabi-aspects/jobs/45504605), but should not.

`mvn -version` returns the following:
```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T12:59:23-04:30)
Maven home: d:\apps\apache-maven-3.2.5\bin\..
Java version: 1.6.0_45, vendor: Sun Microsystems Inc.
Java home: c:\Program Files\Java\jdk1.6.0_45\jre
Default locale: ru_RU, platform encoding: Cp1251
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
```

**Comment by dmarkov** [comment]
this task will get someone's attention soon

**Comment by dmarkov** [comment]
@apocarteres can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by dmarkov** [comment]
@darkled many thanks for the report, I topped your account for 15 mins, transaction 49717531

**Comment by darkled** [comment]
@dmarkov is it ok that actual transaction id is equal to your number +1 ?

**Comment by apocarteres** [comment]
sure. let me check it

**Comment by apocarteres** [comment]
@darkled did you change any sources before you local build? If so, double check that your text editor / IDE doesn't put not UNIX complaint end of line symbols.

**Comment by darkled** [comment]
@apocarteres it was a clean checked out sources wtihout any changes.

**Comment by apocarteres** [comment]
ok. checking...

**Comment by apocarteres** [comment]
@darkled did you try to run mvn with heap adjusting flags? I figured out that it's OOME issue. The facts below do prove that:

- having used the <code>mvn clean install -Pqulice</code> command build fails and it says that several dependencies were not resolved
- having used the <code>mvn -e clean install -Pqulice</code> the same fail, but now we can see OOME 
![screen shot 2015-01-03 at 5 09 28 pm](https://cloud.githubusercontent.com/assets/3305624/5602249/0fc98eb0-9364-11e4-8f33-fe754a60d0df.png)
- and finally according to gathered info we just abit hack flags for pergen <code>MAVEN_OPTS="-Xms2g -Xmx2g -XX:MaxPermSize=512m" mvn -T 8 -e clean install -Pqulice</code>
![screen shot 2015-01-03 at 5 15 34 pm](https://cloud.githubusercontent.com/assets/3305624/5602253/3adda438-9364-11e4-96cd-9bb2b25f4f56.png)

As far as you can see on screenshot it fixes an issue. 

Can you try to maven with flags mentioned above?

**Comment by apocarteres** [comment]
please pay attention to how to setup MAVEN_OPTS correct on non POSIX/LINUX systems

**Comment by darkled** [comment]
@apocarteres unfortunately `OutOfMemoryError` has nothing to do with this. Please take a look at the [log file](https://gist.github.com/darkled/52818d0f05df5fdb9f68) of `mvn -e clean install -Pqulice`.

**Comment by apocarteres** [comment]
ok then, please check out my fork from <code>https://github.com/apocarteres/jcabi-aspects</code> i just added <code>.gitattributes</code> file. It's going to solve the problem. If so, i will raise PR

**Comment by apocarteres** [comment]
please note, that it must be _clean_ checkout, it will force Git to use <code>.gitattributes</code> file then

**Comment by darkled** [comment]
@apocarteres seems that `git clone https://github.com/apocarteres/jcabi-aspects.git jcabi-aspects2` leads to the same result. I think, I've found the reason, system git config under windows defines `core.autocrlf=true`. Theoretically, your `.gitattributes` should override it, but actually it doesn't. So it seems, that the only solution is to override this property locally either in global or in repository config.

**Comment by apocarteres** [comment]
ok, sounds good. it's not an issue anymore?

**Comment by darkled** [comment]
@apocarteres I think yes, thanks.

Accidently, I've removed my previous comment, therefore I will repeat it shortly here.

`.gitattributes` file leads to the same result as it was before. System git configuration under windows defines `core.autocrlf=true` which processes line endings and, theoretically, it should be overridden by `.gitattributes`, but due to some strange reason it was not. So the only solution here I see is to configure either global git config
````
$ git config --global --add core.autocrlf false
```
or repository-wide config
````
$ git config --add core.autocrlf false
```

**Comment by dmarkov** [comment]
@apocarteres I added **30 mins** to your account, many thanks for working with the project!... +30 to your rating, your total score is +60
