### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-aspects#123]
Copyright sections still feature 2014 as a year.

**Comment by dmarkov** [comment]
I'll find a developer for the task soon...

**Comment by dmarkov** [comment]
@romankisilenko this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by dmarkov** [comment]
@maurezen many thanks for the report, I topped your account for 15 mins, transaction 50045017

**Comment by RomanKisilenko** [comment]
@maurezen Hello, PR request was reviewed and closed, please close this issue.

**Comment by dmarkov** [comment]
@romankisilenko **30 mins** sent to your balance (ID `50616616`), many thanks!... +30 added to your rating, current score is: +420
