### ISSUE TITLE
ClassFormatException during compilation

### ISSUE THREAD

**Issue by RomanKisilenko** [jcabi/jcabi-aspects#124]
```
ip-192-168-3-104:jcabi-aspects roman$ ~/apache-maven-3.2.5/bin/mvn clean compile
[INFO] --- aspectj-maven-plugin:1.4:compile (jcabi-weave-classes) @ jcabi-aspects ---
[WARNING] bad version number found in /Users/roman/.m2/repository/org/aspectj/aspectjrt/1.8.4/aspectjrt-1.8.4.jar expected 1.6.11 found 1.8.4
org.aspectj.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 18
	at org.aspectj.apache.bcel.classfile.Constant.readConstant(Constant.java:133)
```
```
ip-192-168-3-104:jcabi-aspects roman$ ~/apache-maven-3.2.5/bin/mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T21:29:23+04:00)
Maven home: /Users/roman/apache-maven-3.2.5
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
Default locale: ru_RU, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.5", arch: "x86_64", family: "mac"
```

**Comment by yegor256** [comment]
@RomanKisilenko can you please post a bigger log. I don't understand what the problem is. say a few more words about the bug

**Comment by RomanKisilenko** [comment]
Here is a full log: https://gist.github.com/RomanKisilenko/d54c8d72caf2ebfb5f43.

Probably the issue is related to a specific environment, but in this case it might be good idea to specify constraints imposed on developer environment.

**Comment by yegor256** [comment]
looks like we can't build with Java8

**Comment by dmarkov** [comment]
@dpisarenko please go ahead with this task, it's yours

**Comment by dpisarenko** [comment]
@dmarkov I can't reproduce exactly the error on my machine with the Java version given below.

```
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) Client VM (build 25.20-b23, mixed mode)
```

@RomanKisilenko posted a build log, where the error occured right at the start, in the compile phase. On my machine, it doesn't occur in the compile phase.

`mvn clean install -Pqulice` runs sucessfully.

**Comment by dpisarenko** [comment]
@dmarkov I'll upgrade my Java to `1.8.0_25` and look, if the error occurs then.

**Comment by dpisarenko** [comment]
@dmarkov I can't reproduce this error under Java version given below, either.

```
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) Client VM (build 25.25-b02, mixed mode)
```

**Comment by dpisarenko** [comment]
FYI: Will now set the version of aspectjrt to 1.8.4 and see, if the error occurs then.

```
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
            <scope>compile</scope>
            <version>1.8.4</version>
        </dependency>
```

**Comment by dpisarenko** [comment]
Now I can reproduce the error.

**Comment by dpisarenko** [comment]
FYI:

  1. I fixed the original problem using a different version of AspectJ Maven plugin (source: http://stackoverflow.com/questions/25155905/running-jdk8-for-aspectj ).
  1. But now, a test fails (see below). I will ignore it and add a puzzle for it.

```
Failed tests:
  CacheableTest.cachesSimpleCall:61
Expected: "-3213197899925110139"
     but: was "-3304694925357223245"
```

**Comment by dpisarenko** [comment]
@dmarkov Please find someone to review my pull request https://github.com/jcabi/jcabi-aspects/pull/126 .

**Comment by yegor256** [comment]
@dpisarenko thanks for explaining your progress, very good practice!

**Comment by dpisarenko** [comment]
@RomanKisilenko The issue has been fixed and the bugfix merged. Please check, if it works and if it does, close the issue. Thanks!

**Comment by RomanKisilenko** [comment]
It compiles for me fine now.

**Comment by dmarkov** [comment]
@dpisarenko Thanks a lot, I just topped your account for **30 mins**, transaction ID `50517963`

+30 added to your rating, at the moment it is: [+235](http://www.netbout.com/b/35089?open=rating)

**Comment by RomanKisilenko** [comment]
@dmarkov Is not I'm supposed to be paid for this bug report?

**Comment by yegor256** [comment]
@dmarkov please add extra 15 mins to @RomanKisilenko

**Comment by dmarkov** [comment]
> @dmarkov please add extra 15 mins to @RomanKisilenko 

@yegor256 15 mins extra was just paid to @romankisilenko, transaction `50593136`

**Comment by dmarkov** [comment]
once `124-0ed2a036` puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by dmarkov** [comment]
last puzzled solved `124-0ed2a036`/#133

**Comment by MwumLi** [comment]
if you come here for cas@4.0.0 compilation question, you can use java7 to compile it

**Comment by imcaizheng** [comment]
Same problem encountered. 

Here's the error output:
> [INFO] --- jcabi-maven-plugin:1.0-SNAPSHOT:ajc (default) @ my-app ---
> [INFO] jcabi-aspects 0.22.6/3f0a1f7 started new daemon thread jcabi-loggable for watching of @Loggable annotated meth
> ods
> [INFO] Unwoven classes will be copied to /home/aaron/my-app/target/unwoven
> [INFO] jcabi-aspects 0.22.6/3f0a1f7 started new daemon thread jcabi-cacheable-clean for automated cleaning of expired
>  @Cacheable values
> [INFO] jcabi-aspects 0.22.6/3f0a1f7 started new daemon thread jcabi-cacheable-update for async update of expired @Cac
> heable values
> org.aspectj.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
>         at org.aspectj.apache.bcel.classfile.Constant.readConstant(Constant.java:139)
>         at org.aspectj.apache.bcel.classfile.ConstantPool.<init>(ConstantPool.java:98)
>         at org.aspectj.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:186)
>         at org.aspectj.apache.bcel.classfile.ClassParser.parse(ClassParser.java:131)
>         at org.aspectj.weaver.bcel.BcelWeaver.addAspectsFromJarFile(BcelWeaver.java:260)
>         at org.aspectj.weaver.bcel.BcelWeaver.addLibraryJarFile(BcelWeaver.java:236)
>         at org.aspectj.ajdt.internal.core.builder.AjBuildManager.initBcelWorld(AjBuildManager.java:874)
>         at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:249)
>         at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:185)
>         at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
>         at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
>         at org.aspectj.tools.ajc.Main.run(Main.java:371)
>         at com.jcabi.maven.plugin.AjcMojo.executeAJC(AjcMojo.java:285)
>         at com.jcabi.maven.plugin.AjcMojo.execute_aroundBody2(AjcMojo.java:264)
>         at com.jcabi.maven.plugin.AjcMojo$AjcClosure3.run(AjcMojo.java:1)
>         at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
>         at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
>         at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspec
> ts_aj_MethodLogger$wrap(MethodLogger.java:1)
>         at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:169)
>         at com.jcabi.maven.plugin.AjcMojo.execute_aroundBody4(AjcMojo.java:245)
>         at com.jcabi.maven.plugin.AjcMojo$AjcClosure5.run(AjcMojo.java:1)
>         at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
>         at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:138)
>         at com.jcabi.maven.plugin.AjcMojo.execute(AjcMojo.java:245)
>         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
>         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
>         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
>         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuild
> er.java:51)
>         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
>         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
>         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
>         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
>         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
>         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
>         at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Feb 01, 2018 1:50:14 PM org.aspectj.weaver.tools.Jdk14Trace info

My `mvn --version`:
> Apache Maven 3.5.0
> Maven home: /usr/share/maven
> Java version: 1.8.0_161, vendor: Oracle Corporation
> Java home: /usr/lib/jvm/java-8-oracle/jre
> Default locale: en_HK, platform encoding: UTF-8
> OS name: "linux", version: "4.13.0-32-generic", arch: "amd64", family: "unix"

And the jcabi plugin in my `pom.xml`:
>       <plugin>
>         <groupId>com.jcabi</groupId>
>         <artifactId>jcabi-maven-plugin</artifactId>
>         <version>1.0-SNAPSHOT</version>
>         <executions>
>           <execution>
>             <configuration>
>               <source>1.8</source>
>               <target>1.8</target>
>             </configuration>
>             <goals>
>               
>               <goal>ajc</goal>
>             </goals>
>           </execution>
>         </executions>
>         <dependencies>
>           <dependency>
>             <groupId>com.jcabi</groupId>
>             <artifactId>jcabi-aspects</artifactId>
>             <version>0.22.6</version>
>           </dependency>
>           <dependency>
>             <groupId>org.aspectj</groupId>
>             <artifactId>aspectjrt</artifactId>
>             <version>1.8.13</version>
>           </dependency>
>           <dependency>
>             <groupId>org.hibernate</groupId>
>             <artifactId>hibernate-validator</artifactId>
>             <version>5.0.0.Final</version>
>             <scope>runtime</scope>
>           </dependency>
>         </dependencies>
>       </plugin>

I'm fairly new to Maven and have no idea how to troubleshoot this issue myself.
