### ISSUE TITLE
Qulice configuration - no license specified.

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-aspects#130]
1. Checkout master branch
2. run `mvn qulice:check -Pqulice`
3. There are multiple `Line does not match expected header line of ' * BSD License'. (HeaderCheck)` messages.

This is a known bug of qulice configuration in parent-0.31 (jcabi/jcabi-parent#19), accessed via jcabi-0.16. Suggested action is waiting until jcabi/jcabi#297 fix is released and upgrading jcabi version.

**Comment by yegor256** [comment]
There is no urgent need to upgrade to a new parent.

**Comment by maurezen** [comment]
@yegor256 please correct me if I understand this wrong, but are you saying that fixing failing code style checks in master are LESS important than updating a copyright section (issue #123, labeled by you as a valid bug and already fixed)?
