### ISSUE TITLE
ImmutableTest.java:68-73: This test and the next...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aspects#131]
Puzzle `128-1ba0b794` in `src/test/java/com/jcabi/aspects/ImmutableTest.java:68-73` has to be resolved: This test and the next one are ignored because this functionality was removed in #128. It simply didn't work correctly and I didn't manage to reproduce it. I suspect that that the issue appears when one constructor is calling another constructor. Anyway, let's try to investigate and re-implement the functionality again.... The puzzle was created by Yegor Bugayenko on 20-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@maurezen it's your task, go ahead

**Comment by maurezen** [comment]
@yegor256 @dmarkov I need additional information, so I created an information request ticket on which I depend: #132

**Comment by maurezen** [comment]
@yegor256 @dmarkov created a pull request here #135

**Comment by maurezen** [comment]
@dmarkov @yegor256 pull request #135 merged to master, please close the issue.

**Comment by maurezen** [comment]
@dmarkov @yegor256 ping. please close the issue.

**Comment by maurezen** [comment]
@dmarkov @yegor256 ping. please close the issue.

**Comment by maurezen** [comment]
@dmarkov @yegor256 ping. please close the issue.

**Comment by dmarkov** [comment]
@maurezen Many thanks! **30 mins** were added to your account in Transaction ID `51644587`... +30 added to your rating, at the moment it is: [+1155](http://www.netbout.com/b/35102?open=rating)

**Comment by dmarkov** [comment]
Thanks all, closed
