### ISSUE TITLE
Incomplete documentation: @Immutable

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-aspects#132]
The javadoc needs a strict definition of what is and what isn't an immutable class.

For example, while working on #131, I see in `ImmutableTest#catchesMutableTypesWithInterfaces` that the `@Immutable` is supposed to throw an exception upon initialization of the following class

```java
    private interface MutableInterface {
    }

    @Immutable
    private static final class MutableWithInterface {
        private final transient MutableInterface data = null;
    }
```

Why is that? The `data` field is quite immutable; moreover, the `TruelyImmutable` test class features the final transient fields of the types which are not bearing the `@Immutable` annotation, and that is supposed to be right.

Another example of not-so-obvious design is `MutableWithImmutableInterface` which is supposed to be breaking immutability. Are implementations of `@Immutable` interfaces required to be `@Immutable`, too?

**Comment by yegor256** [comment]
@maurezen this description is not clear enough: http://aspects.jcabi.com/annotation-immutable.html ?

It says: "Our immutability checker is rather strict and doesn't allow classes to have any non-private, non-final properties in order to be called truly immutable. If your class/interface has a property with a type that is an interface, that child interface has to be annotated with @Immutable"

**Comment by maurezen** [comment]
@yegor256 Right, haven't checked the actual docs (shouldn't that paragraph be duplicated in javadoc?). That answers my first question.

The second question still stands. The `impl` field of the `MutableWithImmutableInterface` is private, final and of `@Immutable` type `ImmutableInterface`. What's wrong (initialization to an anonymous implementation without @Immutable interface probably is, but that should be spelled out)?

**Comment by yegor256** [comment]
@maurezen please show the Java code you can't understand

**Comment by maurezen** [comment]
@yegor256 See `ImmutableTest#catchesMutableTypesWithImplementationOfImmutableInterface`.
```java
    @Test(expected = IllegalStateException.class)
    public void catchesMutableTypesWithImplementationOfImmutableInterface() {
        final MutableWithImmutableInterface obj =
            new MutableWithImmutableInterface();
        // @checkstyle MagicNumberCheck (1 line)
        obj.getImpl().willBreakImmutability(5);
    }
```
Why is the exception expected? Docs say that immutability is checked during instantiation, not a word about other methods being checked for mutations.

**Comment by yegor256** [comment]
@maurezen what's inside `MutableWithImmutableInterface`?

**Comment by maurezen** [comment]
@yegor256 

```java
    @Immutable
    private static final class MutableWithImmutableInterface {
        private final ImmutableInterface impl = new ImmutableInterface() {
            private int state = 1;
            @Override
            public void willBreakImmutability(final int newstate) {
                this.state = newstate;
            }
        };
        public ImmutableInterface getImpl() {
            return this.impl;
        }
    }
```

**Comment by yegor256** [comment]
@maurezen this implementation of `ImmutableInterface` is mutable, as you see. That's why the test fails. Looks correct to me. Or I missed the problem?

**Comment by maurezen** [comment]
@yegor256 the implementation itself is an anonymous class without an `@Immutable` annotation, so it is fine to do whatever it wants. The `impl` field is private, final and of the type annotated as `@Immutable`. Where exactly is this breaking the contract as written in your docs quote?

**Comment by yegor256** [comment]
@maurezen `impl` is fine, the problem is with `state` field, which is not `final`

**Comment by maurezen** [comment]
@yegor256 `state` is a field of the class not annotated with `@Immutable`, what's the problem?

**Comment by yegor256** [comment]
@maurezen `ImmutableInterface` doesn't have `@Immutable` annotation?

**Comment by maurezen** [comment]
@yegor256 `size` is a field of an anonymous class which is not annotated. As far as I know, annotations are not inherited in Java, so if jcabi-aspects behaves in another way, it should be documented.

**Comment by maurezen** [comment]
@yegor256 `size` is a field of an anonymous class which is not annotated. As far as I know, annotations are not inherited in Java, so if jcabi-aspects behaves in another way, it should be documented, shouldn't it?

**Comment by yegor256** [comment]
@maurezen it's not annotated, but jcabi-aspects is smart enough to catch this situation. The class `MutableWithImmutableInterface` is mutable, since there is a mutable field inside one of its fields. That's why we complain. Looks correct to me.

**Comment by maurezen** [comment]
@yegor256 I'm fine with this behaviour, too, but shouldn't it be explicitly mentioned in the docs? Since by default java behaves in other way?

**Comment by maurezen** [comment]
@yegor256 any comments?

**Comment by yegor256** [comment]
@maurezen I think our documentation is fine as it is. An object is immutable when all all its components (properties) are immutable.

**Comment by maurezen** [comment]
@yegor256 I'm not arguing with that. I'm saying that if the implementation of `@Immutable` interface is not itself annotated as `@Immutable`, Java doesn't inherit the annotation, and if jcabi-aspects does, it should be mentioned somewhere.
Anyway, you told me about the current logic already, thanks.

**Comment by maurezen** [comment]
@yegor256 sorry, just to reiterate, because I now fail to understand it again.

`ImmutabilityChecker#after` is an aspect which catches instantiations of `@Immutable` classes:
```java
   @After("initialization((@com.jcabi.aspects.Immutable *).new(..))")
```
Let's take a look at the following code now:

```java
@Immutable
interface A{}

class B implements A{}
```
Here `B.class.getAnnotations()` will return an empty array. `B` is not `@Immutable`. Therefore, `ImmutabilityChecker#after` aspect won't bind to a `new B()` invocation.

Looks like aspectj is not smart enough to catch this situation (unless we add `@Inherited` to the `@Immutable` definition). Does that make sense?

**Comment by yegor256** [comment]
@maurezen adding `@Inherited` sounds like a good idea!

**Comment by yegor256** [comment]
@maurezen which code doesn't work as expected? can you show an example?

**Comment by maurezen** [comment]
@yegor256 please see `ImmutableTest#catchesMutableTypesWithImplementationOfImmutableInterface` earlier in the thread. There an anonymous implementation of `@Immutable` is expected to be treated as `@Immutable`, while it actually should not be.

**Comment by yegor256** [comment]
@maurezen post a code example again pls if you want it to be reconsidered. try to save your time and my time. if you need a problem to be solved, try to explain it with all details and present it properly. we discourage generic discussions.

**Comment by maurezen** [comment]
@yegor256 okay.
`ImmutabilityChecker#after` is an aspect which catches instantiations of `@Immutable` classes:
```java
   @After("initialization((@com.jcabi.aspects.Immutable *).new(..))")
```
Let's take a look at the following code now:
```java
    @Test(expected = IllegalStateException.class)
    public void catchesMutableTypesWithImplementationOfImmutableInterface() {
        final MutableWithImmutableInterface obj =
            new MutableWithImmutableInterface();
        // @checkstyle MagicNumberCheck (1 line)
        obj.getImpl().willBreakImmutability(5);
    }
    @Immutable
    private static final class MutableWithImmutableInterface {
        private final ImmutableInterface impl = new ImmutableInterface() {
            private int state = 1;
            @Override
            public void willBreakImmutability(final int newstate) {
                this.state = newstate;
            }
        };
        public ImmutableInterface getImpl() {
            return this.impl;
        }
    }
```

Why is the exception expected? Here `impl.getClass().getAnnotations()` will return an empty array. `impl` is not `@Immutable`. Therefore, `ImmutabilityChecker#after` aspect won't bind to the `impl` initialization and the test should not expect an exception - unless `@Immutable` is itself annotated with `@Inherited`, which is not the case at the moment.

**Comment by yegor256** [comment]
@maurezen this code triggers the AspectJ advice: `new MutableWithImmutableInterface()`. Once it's triggered, we go deeper through the object hierarchy checking every property of every object. As soon as find anything mutable, we raise an exception.

**Comment by maurezen** [comment]
@yegor256 so we find a private final property `impl` of `@Immutable` type, which is fine. The anonymous class that `impl` is initialized to is not a property of the `MutableWithImmutableInterface` and it won't be checked.

**Comment by yegor256** [comment]
@maurezen now I see what you mean. You should have just deleted the tests in the original ticket and that's it

**Comment by maurezen** [comment]
@yegor256 can't do that if I don't understand the intention of the test and implementation, right? Having checked that I do, I can delete them.

**Comment by yegor256** [comment]
@maurezen for the future, keep in mind that it's better to test your assumptions with a pull request instead of a question. if you're not sure, make some minimum changes and send a pull request. if it will be accepted, you were right and can move one. if it will be reject, you will get the answer and will change you direction.
