### ISSUE TITLE
CacheableTest.java:57-58: Make sure that this test...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aspects#133]
Puzzle `124-0ed2a036` in `src/test/java/com/jcabi/aspects/CacheableTest.java:57-58` has to be resolved: Make sure that this test runs under Java 8 and remove the Ignore annotation then.... The puzzle was created by Dmitri Pisarenko on 16-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
the code made here contains a puzzle `33-e5af3af3`/#49, which will be resolved soon

**Comment by dmarkov** [comment]
@nhekfqn the task is yours, go ahead

**Comment by nhekfqn** [comment]
@dmarkov PR created https://github.com/jcabi/jcabi-aspects/pull/136

**Comment by nhekfqn** [comment]
@dmarkov related PR has been merged.

**Comment by nhekfqn** [comment]
@dmarkov can we please close the ticket?

**Comment by dmarkov** [comment]
Closing, thanks all

**Comment by dmarkov** [comment]
@nhekfqn Thanks so much! Your account was topped up for **30 mins** (transaction ID is `51644598`); +30 added to your rating, at the moment it is: [+165](http://www.netbout.com/b/35123?open=rating)
