### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by playing** [jcabi/jcabi-aspects#138]
Successful, but I have a little advice. Sometimes there would be a more complex return value when I used, so I didn't want to output in logger. I viewed the code and didn't find the switch of whether to output the return value. I feel that the switch may use more convenient.

**Comment by yegor256** [comment]
@playing you can use `skipReturn` flag:

```java
@Loggable(skipReturn = true)
public VeryBigObject makeIt() {
  // ...
}
```

**Comment by playing** [comment]
@yegor256 thank you, I find "skipResult" in the annocation.

**Comment by yegor256** [comment]
@playing glad it helped. please close the ticket
