### ISSUE TITLE
Class-level Loggable annotation not woven by Maven plugin

### ISSUE THREAD

**Issue by Agathia** [jcabi/jcabi-aspects#139]
Hi

I am in the process of converting my ANT-based webapp project to use Maven and am having trouble getting the **Loggable** annotation working where it is defined at the class level.

It would appear that when **Loggable** annotation is set on the class, the weaving isn't taking place, but when **Loggable** is set on a method, it works just fine.

The class-level annotations worked without issue in my ANT build, so am wondering if I am missing something somewhere.

The pom.xml below (stripped enough to show the issue) has the jetty plugin defined and I am testing by running:
    `mvn clean  compile jcabi:ajc jetty:run`

Any suggestions that you could provide would be very much appreciated. Love your work!

Minimal `pom.xml`:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.agathia</groupId>
  <artifactId>jcabitest</artifactId>
  <packaging>war</packaging>
  <version>0.0.1-SNAPSHOT</version>
  <name>com.agathia.jcabitest Maven Webapp</name>
  <url>http://maven.apache.org</url>

  <dependencies>

    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>3.1.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.jcabi</groupId>
      <artifactId>jcabi-aspects</artifactId>
      <version>0.20.1</version>
    </dependency>
    <dependency>
      <groupId>org.aspectj</groupId>
      <artifactId>aspectjrt</artifactId>
      <version>1.6.12</version>
    </dependency>
    <dependency>
      <groupId>com.jcabi</groupId>
      <artifactId>jcabi-log</artifactId>
      <version>0.16</version>
    </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>jstl</artifactId>
      <version>1.2</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.1.2</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>jcl-over-slf4j</artifactId>
      <version>1.7.10</version>
    </dependency>
  </dependencies>
  <build>
    <finalName>jcabitest</finalName>
    <pluginManagement>
      <plugins>
        <!-- plugin to weave in jcabi-aspects for logging -->
        <plugin>
          <groupId>com.jcabi</groupId>
          <artifactId>jcabi-maven-plugin</artifactId>
          <version>0.12</version>
          <executions>
            <execution>
              <goals>
                <goal>ajc</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>

      <plugin>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-maven-plugin</artifactId>
        <version>9.1.0.v20131115</version>
        <configuration>
          <webApp>
            <contextPath>/</contextPath>
          </webApp>
        </configuration>
        <dependencies>

          <!-- Have to override Jetty’s dependencies to ASM. In Maven’s POM,
            amend Jetty plugin to force ASM versions: -->
          <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm</artifactId>
            <version>5.0.2</version>
          </dependency>
          <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm-commons</artifactId>
            <version>5.0.2</version>
          </dependency>
        </dependencies>
      </plugin>


    </plugins>
  </build>
</project>
```

A sample servlet:
```java
package com.agathia.jcabitest;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.jcabi.aspects.Loggable;

@Loggable(Loggable.INFO)
public class WelcomeServlet extends HttpServlet {

	private static final long serialVersionUID = 5682119548589338868L;

	/** The Constant LOG. */
	private static final transient Logger LOG = LoggerFactory
			.getLogger(WelcomeServlet.class);

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * javax.servlet.http.HttpServlet#doGet(javax.servlet.http.HttpServletRequest
	 * , javax.servlet.http.HttpServletResponse)
	 */
	@Override
        // uncomment the line below, and logging works for this method
	// @Loggable(Loggable.INFO)
	protected void doGet(final HttpServletRequest request,
			final HttpServletResponse response) throws ServletException,
			IOException {
		response.setContentType("text/plain");
		final PrintWriter writer = response.getWriter();
		writer.print("Welcome!");
		writer.flush();

		callMethod1();
		callMethod2();
	}

	private void callMethod2() {
		LOG.info("in callMethod1()");
	}

	private void callMethod1() {
		LOG.info("in callMethod2()");
	}

}
```

**Comment by yegor256** [comment]
@Agathia when being used at class level, `@Loggable` doesn't touch `protected` and `private` methods. Only `public` methods are logged. I think this is where the problem is.

**Comment by yegor256** [comment]
@Agathia btw, instead of that static `LOG`, you can use Logger from jcabi-log, see: http://log.jcabi.com/

**Comment by Agathia** [comment]
Hi @yegor256

Thanks for your fast response! Changing those private methods to public made a difference in my simple app, but in my main app it is still not working for public methods.

One thing that I have noticed is that when I start the minimal app (`mvn clean compile jcabi:ajc jetty:run`) and access the servlet with the `Loggable` annotation, the following statement is printed to STDOUT:
    `2015-02-14 15:24:57,479 INFO [qtp1199568792-27] c.j.a.a.NamedThreads [Logger.java:193] jcabi-aspects 0.20.1/f0aff93 started new daemon thread jcabi-loggable for watching of @Loggable annotated methods`

This log entry does not appear for my own app with the same commandline. My logback.xml for both apps has:
```xml
<root level="INFO">
```
When I was compiling your aspects into my app with ANT, I was forcing compile-time weaving, whereas your Maven plugin appears to use load-time. Is there any way to force the Maven plugin to do compile-weaving?

**Comment by yegor256** [comment]
@Agathia I'm not sure what you mean by "load-time". Let's try step by step. First, place jcabi-maven-plugin into `plugins` section. Now it's in `pluginManagement`, which is wrong.

**Comment by Agathia** [comment]
@yegor256 OK, I moved the plugin out of `<pluginManagement>` and now it is logging correctly! I am really grateful for your help and fast responses, thanks!

The reason I moved it into `<pluginManagement>` was because it was suggested on StackOverflow as a fix to an error that I was/am seeing in Eclipse:
`Plugin execution not covered by lifecycle configuration: com.jcabi:jcabi-maven-plugin:0.12:ajc (execution: default, phase: process-classes)`

This error doesn't seem to affect the build. Is it safe to mark it ignored, or should I add something to my pom.xml?

**Comment by yegor256** [comment]
@Agathia it's something you should figure out between you and Eclipse :) I've seen this error many times and I don't know how to fix it. I think that Eclipse just can't understand our plugin. If you find a solution, let me know. In the mean time, please close this ticket if the problem is solved. Thanks for using our lib :)

**Comment by Agathia** [comment]
@yegor256 Thanks again for your support. Love the lib!

**Comment by Agathia** [comment]
@yegor256 Just found this thread on (http://stackoverflow.com/a/6372575StackOverflow) showing the same issue with a different plugin. With the snippet below in my `pom.xml`, the error goes away and the build still works correctly. This is in addition to having the jcabi-maven-plugin defined outside of the `<pluginManagement>` element.
 
```xml
    <pluginManagement>
      <plugins>
        <!--This plugin's configuration is used to store Eclipse m2e settings
          only. It has no influence on the Maven build itself. -->
        <plugin>
          <groupId>org.eclipse.m2e</groupId>
          <artifactId>lifecycle-mapping</artifactId>
          <version>1.0.0</version>
          <configuration>
            <lifecycleMappingMetadata>
              <pluginExecutions>
                <pluginExecution>
                  <pluginExecutionFilter>
                    <groupId>com.jcabi</groupId>
                    <artifactId>jcabi-maven-plugin</artifactId>
                    <versionRange>[0.0,)</versionRange>
                    <goals>
                      <goal>ajc</goal>
                    </goals>
                  </pluginExecutionFilter>
                  <action>
                    <execute />
                  </action>
                </pluginExecution>
              </pluginExecutions>
            </lifecycleMappingMetadata>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
```

**Comment by yegor256** [comment]
@Agathia wow, thanks for the hint. How about we make a page on our website (aspects.jcabi.com) with a page for Eclipse users and this example you just showed? Can you make it and submit a pull request? All users will benefit from this knowledge :)
