### ISSUE TITLE
Arrays immutability assertion options

### ISSUE THREAD

**Issue by super132** [jcabi/jcabi-aspects#157]
In #49 , we try to create an aspect which checks if an array field in a class is immutable by perform checking on setting new values to the array. Based on the link [bug link](https://bugs.eclipse.org/bugs/show_bug.cgi?id=157031) from AspectJ, up to this moment AspectJ does NOT support array field checking pointcut. However, there is a work done to have array point cut for get / set operations on arrays. This [implementation](http://www.geocities.ws/m8809301/work/ArrayPT/ArrayPT.html) is based on "[The AspectJ Bench Compiler](http://www.sable.mcgill.ca/abc/introduction)" (abc), which is an AspectJ compiler with extension feature, and create extension to "abc" to acheive such purpose. Given that "abc" has not been updated for years (the latest release is in 2008), it does not guarantee to work in latest JDK. Also, by using "abc" that means we are not using AspectJ compiler and it may conflicts to the design principle of `jcabi-aspects` to solely depends on AspectJ.

With the options that I have exposed, I can think of the options below:

### Option 1 - Implement the use of array point cut by using abc
This option is to examine and implement the use of abc to replace ajc for aspect compilation and weaving, in order to support array point cut for get / set operations. Then develop an aspect to select array set point cut and throw exception. However, it leads to use unsupported library codes and abc is not updated for 7 years.

### Option 2 - Re-implement array point cut in AspectJ
This option is to study and re-implement the array point cut for abc in AspectJ and contribute to AspectJ project. With this option, `jcabi-aspects` can still depends on AspectJ library and benefit from the latest array point cut features. The development effort is, however, is not trivial and requires desirable amount of time.

### Option 3 - Forbid the use of array fields in `@Immutable` classes
This option is to stick with what we have now in AspectJ and not introducing unsupported libraries, but to forbid the use of array in `@Immutable` classes due to the fact that we cannot guard the assignment to an array element field. More information can be provided in the exception to tell users to use `Collection` or `Iterable` classes. Then, advice can be developed for `Collection` or `Iterable` or even `List` classes.

May I know in which way should we handle #49 ? Thanks.

**Comment by super132** [comment]
@yegor256 , may I have your advice on decision of handling array immuatability ? Thanks.

**Comment by yegor256** [comment]
@super132 many thanks for the analysis you made... unfortunately, none of these options look good to me :( I think we should just postpone task #49 for unknown amount of time.

**Comment by super132** [comment]
@yegor256 understood. Should we keep this ticket open as well ?

**Comment by yegor256** [comment]
@super132 no, this one is not a valid bug, it's more a discussion ticket. I think you should just close it

**Comment by super132** [comment]
@yegor256 . understood. I'm closing it. Thanks.
