### ISSUE TITLE
Logger is tightly coupled to SLF4J

### ISSUE THREAD

**Issue by dakbhavesh** [jcabi/jcabi-aspects#158]
I find this API quite useful. Only one thing which is holding me up from using it is that its tightly coupled with SLF4J logger. Is there any way I can tell use org.apache.commons.logging.Log instead of org.slf4j.Logger.
Logger class is not final so we can override the implementation. 
Would be great if user can use any logger framework.

"Code quality is really nice. Appreciate it."

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@dakbhavesh that's what SLF4J is for - to give you an ability to use any logging facility you like. Just add a connector between SLF4J and common logging and you're done. more information here: http://www.slf4j.org/manual.html
