### ISSUE TITLE
Need a sample maven project which uses @Loggable.

### ISSUE THREAD

**Issue by piyusht007** [jcabi/jcabi-aspects#159]
Hi,
I was trying to include jcabi aspects in my project however due to some reason I am not able to see the logs. It will be very grateful If somebody can provide a sample maven project from which I can see the logs in eclipse console or in the log file. 

Just a class and a method with @Loggable annotation over it will serve the purpose. This library seems very useful and I am looking forward for the responses.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by dmarkov** [comment]
@pecko the task is yours

**Comment by pecko** [comment]
@dmarkov 

I have created a project. Where I would be upload it?

**Comment by pecko** [comment]
@dmarkov 

I have created https://github.com/pecko/loggable. README explains how to use it.

**Comment by dmarkov** [comment]
> @dmarkov 
> 
> I have created a project. Where I would be upload it?
> 
> 

@pecko @yegor256 what do you think?

**Comment by dmarkov** [comment]
> @dmarkov 
> 
> I have created https://github.com/pecko/loggable. README explains how to use it.

@pecko you should offer this to the ticket author, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by pecko** [comment]
@piyusht007 

I have created https://github.com/pecko/loggable. README explains how to use it.
Please review.

**Comment by piyusht007** [comment]
@pecko  Thanks I've reviewed the project and it is working fine. Though I noticed one error in the pom.xml which says "Plugin execution not covered by lifecycle configuration".

You can use <pluginManagement> tag to wrap <plugins> tag and this error will go away.

**Comment by pecko** [comment]
@piyusht007 

>  "Plugin execution not covered by lifecycle configuration".

It's m2e issue or feature :(. I have described it in README. You can do the following:

- call Quick Fix and ignore error
- create m2e configurator for the jcabi-maven-plugin plugin :) 

It is reason that you have call maven build manually from Eclipse.

**Comment by pecko** [comment]
@dmarkov 

This project is closed now. What we should to do yet?

**Comment by dmarkov** [comment]
> @dmarkov 
> 
> This project is closed now. What we should to do yet?

@pecko just wait a bit

**Comment by dmarkov** [comment]
@pecko Much obliged! I have added **30 mins** to your account in payment "67397589", 139 hours and 11 mins spent. +30 added to your rating, current score is: [+105](http://www.netbout.com/b/35660?open=rating)
