### ISSUE TITLE
Tv(time values) shouldn't be a Constants Interface

### ISSUE THREAD

**Issue by simonjenga** [jcabi/jcabi-aspects#160]
The ```Constants Interface``` is usually not recommended as a good design practice.

Perharps ```com.jcabi.aspects.Tv``` should be a ```final``` class with a ```private``` default constructor to ensure non-instantiability. 

In doing so, we would not be breaking any existing functionality with any classes that depend on it and also, we would prevent any future accidental implementations of ```com.jcabi.aspects.Tv```.

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@simonjenga I believe it's fixed in #164 and we can close this ticket?
