### ISSUE TITLE
src/main/java is marked as a resources directory

### ISSUE THREAD

**Issue by Suseika** [jcabi/jcabi-aspects#167]
In  `/pom.xml`, in `<build>` section, `/src/main/java` directory is marked as a resources directory. Because of that IntelliJ IDEA doesn't recognize its contents as source code and it is impossible to work with those sources.

If that directory contents is indeed supposed to be resources, then it shouldn't be named `/src/main/java`, because by Maven standards `/src/main/java` must be a source directory.

**Comment by Suseika** [comment]
I see that this is done in order to use project version and build number in logs (see, for example, `ImmutabilityChecker` class for string `${project.version}/${buildNumber}`). 

For me this seems to be a wrong approach. If we absolutely need to do such source code processing, then this should be done with _source processing tools_. Instead we pretend that the sources are resources, and IDE believes that and doesn't treat those sources as sources. This makes the sources unmaintainable.

**Comment by Suseika** [comment]
By the way, removing `/src/main/java` from the list of resource directories doesn't break the build, so either that resource filtering is absolutely redundant, or we're lacking unit tests for the functionality that was achieved with that resource filtering.

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@Suseika it's a valid concern, thanks. I'm not sure how to solve this right, but the bug is there, definitely

**Comment by Suseika** [comment]
@yegor256 There is `replacer` plugin: https://code.google.com/p/maven-replacer-plugin/, I think it is just the right tool for the job.

**Comment by yegor256** [comment]
@Suseika perfect

**Comment by yegor256** [comment]
@dmarkov assign @Suseika to this task pls

**Comment by dmarkov** [comment]
> @dmarkov assign @Suseika to this task pls

@yegor256 OK @suseika please go ahead, this task is yours

**Comment by dmarkov** [comment]
@suseika many thanks for the report, I topped your account for 15 mins, transaction AP-8RL384953P6408434

**Comment by Suseika** [comment]
@dmarkov I need more time on this task

**Comment by Suseika** [comment]
@yegor256 I'm not sure why, but for some reason I got removed from this task the moment I posted the last message. Can I get assigned back?

**Comment by dmarkov** [comment]
> @dmarkov I need more time on this task

@suseika of course, take your time

**Comment by yegor256** [comment]
@Suseika you're still assigned here, see the tag with your name attached (the green one)

**Comment by dmarkov** [comment]
@rultor rultor closed it (automatically), @Suseika please take a look

**Comment by Suseika** [comment]
@Suseika Everything's good. Thanks!

**Comment by dmarkov** [comment]
@suseika the code made here contains a puzzle `167-78e42157`/#174, which will be resolved soon

**Comment by dmarkov** [comment]
@suseika I added **30 mins** to your account, many thanks for working with the project! The completion time here was AP-3P1371553V2970054.. +30 added to your rating, at the moment it is: [+503](http://www.netbout.com/b/35381?open=rating)

**Comment by dmarkov** [comment]
@suseika the last puzzle `167-78e42157`/#174 solved
