### ISSUE TITLE
JointPointUtils is a utility class, it can be replaced with a decorator for JoinPoint

### ISSUE THREAD

**Issue by Suseika** [jcabi/jcabi-aspects#168]
`JoinPoint` is an interface, so it is a perfect candidate for decoration if we need to add additional responsibilities to its instances. However, in this project we have a utility class `JoinPointUtils`. This is a bug, there should be a decorator like `ImprovedJoinPoint` or something instead.

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@Suseika totally agree, thanks!

**Comment by dmarkov** [comment]
@suseika thanks for the report, I topped your acc for 15 mins, payment ID `AP-2KW98265E1112030E`

**Comment by dmarkov** [comment]
@shelan it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by shelan** [comment]
@dmarkov I have created a pull request in #192 . Could you please get it reviewed.

**Comment by dmarkov** [comment]
> @dmarkov I have created a pull request in #192 . Could you please get it reviewed.
> 

@shelan sure, will assign someone soon

**Comment by shelan** [comment]
@Suseika #192  is merged now. Could you please resolve the issue?

Thank you.

**Comment by dmarkov** [comment]
@shelan Much appreciated! **30 mins** was added to your account, payment ID `66774278`, time spent is 169 hours and 4 mins

+30 added to your rating, current score is: [+45](http://www.netbout.com/b/35659?open=rating)
