### ISSUE TITLE
ImmutabilityChecker.java:65-68: Inserting correct version/buildnumber here and...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aspects#174]
Puzzle `167-78e42157` in `src/main/java/com/jcabi/aspects/aj/ImmutabilityChecker.java:65-68` has to be resolved: Inserting correct version/buildnumber here and in other instances where Version.CURRENT is used (not only in this class, but in every class that uses Version.CURRENT) should be covered by a test.... The puzzle was created by Suseika on 21-Jul-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@pecko it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by pecko** [comment]
@dmarkov 

> Feel free to ask any technical questions right here in the ticket

I want to be sure that I understand this task.
Version.CURRENT is used in the com.jcabi.aspects.aj.ImmutabilityChecker and com.jcabi.aspects.aj.NamedThreads

You want me to do the following:
- test that will check that the version/buildnumber is correct (the same as ${projectVersion}/${buildNumber}
or
- add version/buildnumber to all places (exceptions and logs) in these two classes and test it

Notice:
We just can make one test that will test version/buildnumber when instantiate these classes

I also can just do what I think and reviewer will show me the problems.

Suggestion:

We can read version/buildnumber from some properties as I do in: https://github.com/pecko/jcabi-github/commit/14dbcb0def3409bd21cb1bfaf7fb00ff66d6db15 (#932 - see also https://github.com/jcabi/jcabi-github/issues/1163
In this case we don't need create Version.java by templating than use simple maven resource filtering.

Sorry for a lot message. This is my first official task.

**Comment by pecko** [comment]
@dmarkov 
I have done as I understand this. The PR: https://github.com/jcabi/jcabi-aspects/pull/190
Please review.

**Comment by dmarkov** [comment]
> @dmarkov 
> 
> > Feel free to ask any technical questions right here in the ticket
> 
> I want to be sure that I understand this task.
> Version.CURRENT is used in the com.jcabi.aspects.aj.ImmutabilityChecker and com.jcabi.aspects.aj.NamedThreads
> 
> You want me to do the following:
> - test that will check that the version/buildnumber is correct (the same as ${projectVersion}/${buildNumber}
> or
> - add version/buildnumber to all places (exceptions and logs) in these two classes and test it
> 
> Notice:
> We just can make one test that will test version/buildnumber when instantiate these classes
> 
> I also can just do what I think and reviewer will show me the problems.
> 
> Suggestion:
> 
> We can read version/buildnumber from some properties as I do in: https://github.com/pecko/jcabi-github/commit/14dbcb0def3409bd21cb1bfaf7fb00ff66d6db15 (#932 - see also https://github.com/jcabi/jcabi-github/issues/1163
> In this case we don't need create Version.java by templating than use simple maven resource filtering.
> 
> Sorry for a lot message. This is my first official task.

@pecko the puzzle was added to the code by @Suseika - you better ask him for help

**Comment by pecko** [comment]
@Suseika 

Could you, please, clarify the issue?

@dmarkov 

Would I create a new issue?

**Comment by pecko** [comment]
@pinaf @Suseika 

I have update the PR. New commit: https://github.com/pecko/jcabi-aspects/commit/7b4769b6d3534d6312614ae3f1ece31d4d3eed5e

**Comment by pecko** [comment]
The issue is solved. rultor merged it - https://github.com/jcabi/jcabi-aspects/pull/190#issuecomment-144619687

**Comment by dmarkov** [comment]
@yegor256 Closing, thanks all

**Comment by dmarkov** [comment]
@pecko done, I added **30 mins** in payment `66422885`, 77 hours and 21 mins spent to complete this... +30 to your rating, your total score is [+45](http://www.netbout.com/b/35660?open=rating)
