### ISSUE TITLE
Custom annotation using aspectj

### ISSUE THREAD

**Issue by PalakArora** [jcabi/jcabi-aspects#178]
Hi @yegor256,

I am trying to write a custom annoation on the similar lines as @Loggable in jcabi.
I referred to the link: http://www.yegor256.com/2014/06/01/aop-aspectj-java-method-logging.html

After weaving, we got the following code:

```
public class Foo {
  private final MethodLogger logger;
  @Loggable
  public int power(int x, int p) {
    return this.logger.around(point); -----from where did  you get this point?
  }
  private int power_aroundBody(int x, int p) {
    return Math.pow(x, p);
  }
}
```

My question is from where did  you get the variable "point"?
Thanks in advance

**Comment by yegor256** [comment]
@PalakArora I believe it's more a question for StackOverflow, not for this issue tracker :) You want to learn AspectJ, right? Ask question there and email me the link, I will try to help
