### ISSUE TITLE
If I define a new annotation in this project, how I can start it as starting Cacheable

### ISSUE THREAD

**Issue by 54uso** [jcabi/jcabi-aspects#186]
Like this:
[INFO] jcabi-aspects 0.18/55a5c13 started new daemon thread jcabi-cacheable for automated cleaning of expired @Cacheable values

I saw this log at terminal when I started project, but I define a new annotation like Cacheable didn't find log like this.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@54uso I don't understand where exactly is a bug?

**Comment by 54uso** [comment]
@yegor256  Thank u for ur answer. I am sorry for the mistake i made before. Thank you.
