### ISSUE TITLE
Adding JDK7 requirement in README

### ISSUE THREAD

**Issue by pecko** [jcabi/jcabi-aspects#188]
Seems that this project doesn't build with JDK 8 (at least for me on Ubuntu 14.04

```
mvn -version
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)
Maven home: /usr/local/apache-maven-3.2.3
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /usr/local/jdk1.8.0_60/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-65-generic", arch: "amd64", family: "unix"
```

. Maybe we should add that to README.

**Comment by pecko** [comment]
Also, this project requires non-default maven options.

I have to do the following:

```
export MAVEN_OPTS="-Xmx1024M -Xms256M -XX:PermSize=128M -XX:MaxPermSize=256M"
# set Java to JDK 7
mvn clean verify -Pqulice
```

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@pecko maybe it's better to make it work with JDK 8 instead of documenting the bug... we'll try to fix it

**Comment by pecko** [comment]
@yegor256 

Will I update title/description. We can add required maven options to pom.xml.

**Comment by dmarkov** [comment]
@pecko thanks for tis bug, I topped your account for 15 mins, transaction `66490366`

**Comment by dmarkov** [comment]
@nikoladespotoski it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket. This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by NikolaDespotoski** [comment]
@dmarkov assign someone else

**Comment by dmarkov** [comment]
> @dmarkov assign someone else

@nikoladespotoski right, I'll try to find someone else for this task
