### ISSUE TITLE
Question: Testing Logger.info message 

### ISSUE THREAD

**Issue by pecko** [jcabi/jcabi-aspects#191]
I need test logger's message text in https://github.com/jcabi/jcabi-aspects/issues/174

The code (com.jcabi.aspects.aj.NamedThreads.java, lines 80-88):

```
Logger.info(
            this,
            // @checkstyle LineLength (1 line)
            "jcabi-aspects %s/%s started new daemon thread %s for %s",
            Version.CURRENT.projectVersion(),
            Version.CURRENT.buildNumber(),
            this.name,
            this.purpose
        );
```

How I can extract logger's message in order to contains replaced version/buildNumber.

**Comment by Suseika** [comment]
@pecko You can add a `WriterAppender` to the logger `org.apache.log4j.Logger.getRootLogger()` before the log message you're interested in is sent. `WriterAppender` can obtain what is being logged.

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by pecko** [comment]
@dmarkov @yegor256 

@Suseika answered correctly. It helps me to solve #174. 

@Suseika 

Thanks!

**Comment by Suseika** [comment]
@pecko If your question is answered, please close the issue.

**Comment by pecko** [comment]
It is solved.
