### ISSUE TITLE
Cutomize Log Output

### ISSUE THREAD

**Issue by Mustapha-Senhaji** [jcabi/jcabi-aspects#197]
Is it possible to customize the log output by using a file template, a log properties or even by a init class?

**Comment by dmarkov** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@Mustapha-Senhaji no, it's not possible to change log texts.
