### ISSUE TITLE
@ScheduleWithFixedDelay does not work as expected

### ISSUE THREAD

**Issue by simonjenga** [jcabi/jcabi-aspects#200]
The ```com.jcabi.aspects.@ScheduleWithFixedDelay``` schedules a method to run with fixed delay, automatically. Execution will be started as soon as you make an instance of the class with this annotation.

However, the following code does not work as stated in the above documentation.

```
import java.io.Closeable;
import java.io.IOException;
import java.util.concurrent.TimeUnit;

import com.jcabi.aspects.ScheduleWithFixedDelay;

@ScheduleWithFixedDelay(delay = 1, unit = TimeUnit.MINUTES)
public class WithFixedDelay implements Runnable, Closeable {

	@Override
	public void run() {
		try {
			for (;;) {
				System.out.println("....Seasons Greetings!....");
				TimeUnit.SECONDS.sleep(5);
			}
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}
	
	@Override
	public void close() throws IOException {
		System.out.println("Closing!");
		this.close();	
		System.exit(0);
	}

	public static void main(String[] args) {
		new WithFixedDelay();
	}
}
```

Any reasons that can explain this?

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@simonjenga you have to weave your binaries after compilation, see http://aspects.jcabi.com/example-weaving.html

**Comment by simonjenga** [comment]
@yegor256 Unfortunately, i doesn't print out the message: 

 ```System.out.println("....Seasons Greetings!....");```.

The output at the console is:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
Nothing else happens after that. Even after ```1 min```.

**Comment by yegor256** [comment]
@simonjenga there is something wrong with your `pom.xml` or your project. This feature works for at least two years in multiple projects.
