### ISSUE TITLE
todo puzzles are not validated in travis build

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-aspects#203]
There is no validation of todos in travis configuration so they are not catched early by the developer.
Please add this validation using `pdd` tool in similar way as it is done for rultor.

**Comment by dmarkov** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@krzyk it's done already: https://github.com/jcabi/jcabi-aspects/blob/master/.travis.yml#L24
