### ISSUE TITLE
MethodValidator.java:152-156: We need to find a...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aspects#204]
Puzzle `194-8b58eead` in `src/main/java/com/jcabi/aspects/aj/MethodValidator.java:152-156` has to be resolved: We need to find a way to disable the constraint rule OverridingMethodMustNotAlterParameterConstraints instead of catching the exception. See https://hibernate.atlassian.net/browse/HV-1044 After that don't forget to enable test JSR303Test#overridesMessage()... The puzzle was created by Dmitry Zaytsev on 8-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by dmarkov** [comment]
@gmandnepr can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here... The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by gmandnepr** [comment]
@dmarkov pull request created https://github.com/jcabi/jcabi-aspects/pull/206

**Comment by dmarkov** [comment]
> @dmarkov pull request created https://github.com/jcabi/jcabi-aspects/pull/206

@gmandnepr OK

**Comment by gmandnepr** [comment]
@dmarkov pr is merged

**Comment by dmarkov** [comment]
> @dmarkov pr is merged

@gmandnepr thanks

**Comment by dmarkov** [comment]
@gmandnepr thank you, added **30 mins** to your acc, payment num is `75675957`, 170 hours and 52 mins spent in total to complete

added +30 to your rating, now it is equal to [-30](http://www.netbout.com/b/36313?open=rating)

**Comment by dmarkov** [comment]
@yegor256 Closing..
