### ISSUE TITLE
@Cacheable - SoftReference

### ISSUE THREAD

**Issue by dmzaytsev** [jcabi/jcabi-aspects#214]
I would propose to use `SoftReference` inside `@Cacheable` to prevent OutOfMemory errors
see https://docs.oracle.com/javase/7/docs/api/java/lang/ref/SoftReference.html

Maybe usage of `SoftReference` should be optional.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by dmarkov** [comment]
@dmzaytsev thank you for the ticket reported, I topped your account for 15 mins, transaction `79165362`

**Comment by dmarkov** [comment]
@nesterov-n This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by nesterov-n** [comment]
@dmarkov See my PR #217

**Comment by dmarkov** [comment]
> @dmarkov See my PR #217 

@nesterov-n thanks

**Comment by nesterov-n** [comment]
@dmzaytsev PR has been merged. Can you close this issue?

**Comment by dmzaytsev** [comment]
@nesterov-v thanks

**Comment by dmzaytsev** [comment]
@yegor256 please release if possible

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.4`

**Comment by dmarkov** [comment]
@nesterov-n Thanks for your contribution, **30 mins** was added to your account, payment ID is `AP-6J597220CB723445M`, 407 hours and 38 mins spent total... added +30 to your rating, now it is equal to [-58](http://www.netbout.com/b/36483?open=rating)
