### ISSUE TITLE
Error shown in the logs

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-aspects#216]
In one build that runs ``ajc`` using ``jcabi-aspects``, I see the following log. 
Where can I see what was the actual error? It's a bit misleading since there are no ``@Cachable`` annotations in the built project. 

![image](https://cloud.githubusercontent.com/assets/6305156/13627763/79602cde-e5d5-11e5-91a0-50e61da9d46e.png)

**Comment by amihaiemil** [comment]
clarified

**Comment by MauricioJr** [comment]
@amihaiemil could you please share your solution?
Maybe it can help someone in the future.

Thank yoU!

**Comment by amihaiemil** [comment]
@MauricioJr There was no solution found - as I said in the description, I don't know what that error means. I initially thought it was causing a bad behaviour in my build... it turned out that something else was the problem, so I left this aside. 

I reopen this issue, maybe someone answers.

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@amihaiemil can you post a bigger part of the log? also, was the build successful in the end?

**Comment by amihaiemil** [comment]
@yegor256 Yes, the build was successfull. Log in gist https://gist.github.com/amihaiemil/040297c36260031e9a61 (line 37-39) 

The built project is here https://github.com/jcabi/jcabi-maven-plugin/issues/45 - search for ".zip".. for some reason github wouldn't let me upload .zip, maybe because I'm on windows and Winrar detects that file type. 

Built with goals ``clean install assembly:single`` and jdk1.8.0_66 - maybe that's the cause of it.

The problem is that classes aren't woven with ``jcabi-maven-plugin v. 0.14`` and I initially thought that error was causing the behaviour. It turned out the problem was, in fact, this issue : 
https://github.com/jcabi/jcabi-maven-plugin/issues/48

**Comment by yegor256** [comment]
@amihaiemil I don't see what exactly is the problem here... closing
