### ISSUE TITLE
Example using IntelliJ with Java8

### ISSUE THREAD

**Issue by KuchiVanDerK** [jcabi/jcabi-aspects#220]
I'm trying to make the @Loggable run within IntelliJ using Java8.
I don't get any warnings or notifications the @Loggable seems to be ignored.
Do I need to enable anything so IntelliJ recognizes the AspectJ?

Followed the blog post from [aop-aspectj-java-method-logging](http://www.yegor256.com/2014/06/01/aop-aspectj-java-method-logging.html)

The code I tried to run: [loggable-test](https://github.com/KuchiVanDerK/loggable-test)

**Comment by dmarkov** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@KuchiVanDerK you won't be able to make it work from IDE, only from command line when you run `mvn clean test` (or any other build tool you're using). IntelliJ simply doesn't run any Maven plugins, that's the problem.
