### ISSUE TITLE
JSR-349 support

### ISSUE THREAD

**Issue by essobedo** [jcabi/jcabi-aspects#221]
`Bean Validation` 1.1 has been released 3 years ago, do we have any plan to support it? In projects where we use `hibernate-validator` 5.1 or higher, we get errors of type `JSR-303 validator failed to initialize: Unable to instantiate Configuration. (see http://aspects.jcabi.com/jsr-303.html)`. Is it at least possible to avoid such error when we use an implementation of JSR-349 with the current version of jcabi-aspects?

**Comment by MauricioJr** [comment]
Hello Nicolas, thank you for your report.
Could you provide a simple project containing these library setup?

If so, please paste the project link here. We'll fork the repository and
analyze this issue.

Thanks,
MC

**Comment by essobedo** [comment]
@MauricioJr thx for your answer, actually it is a private project so I don't believe that I can share anything but does it mean that it should work? do you support JSR-349?

**Comment by MauricioJr** [comment]
What I asked for is if you can create a test project for us? It should contain the same jar structure (including versions) that you are using on your production project with a simples test class.
About JSR-349, I believe it's the first incompatibility report.

Thank you,
MC

**Comment by essobedo** [comment]
@MauricioJr ok I will try to provide this test project

**Comment by essobedo** [comment]
@MauricioJr I finally find out that my problems come from `jcabi-maven-plugin` sorry for the noice
