### ISSUE TITLE
What are you using to generate version ids on new files?

### ISSUE THREAD

**Issue by westonized** [jcabi/jcabi-aspects#225]
e.g.:

```
/**
 * Test case for {@link Cacheable} annotation and its implementation.
 * @author Yegor Bugayenko (yegor@tpc2.com)
 * @version $Id: ca9877488a58274154311a989f5fd585ef0c0f0f $
 * @checkstyle ClassDataAbstractionCoupling (500 lines)
 */
```

Where did `ca9877488a58274154311a989f5fd585ef0c0f0f` come from? Any neat way to generate in intellij?

And also what are they for?

**Comment by westonized** [comment]
Git seems to replace any id I write in with ``* @version $Id$`` so presumable I can just do that?

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@westonized more info about this you can find here http://stackoverflow.com/questions/1792838/how-do-i-enable-ident-string-for-git-repos
