### ISSUE TITLE
Line does not match expected header line of ' * Copyright (c) 2012-2015, jcabi.com'

### ISSUE THREAD

**Issue by westonized** [jcabi/jcabi-aspects#226]
You get this message if you use 2012-2016 on a new file. Rule needs relaxing, or rule and all files need to be changed to 2016.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@westonized fixed in 9b16577 thanks!
