### ISSUE TITLE
Reduce the log level of the message indicating that there is no JSR-303 provider available

### ISSUE THREAD

**Issue by essobedo** [jcabi/jcabi-aspects#227]
Up to now, when no JSR-303 provider is available in the classpath, it logs an error of type `JSR-303 validator failed to initialize: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.`which is not really appropriate as it could be a perfectly valid situation so the log level should be reduced to have a warning instead of error.

More info https://github.com/jcabi/jcabi/issues/260

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@essobedo it looks like that log line is reported by `javax.validation.Validation`, not by us (correct me if I'm wrong). We simply can't do anything about it.
