### ISSUE TITLE
@loggable doesn't work with Slf4j

### ISSUE THREAD

**Issue by santhosh12992** [jcabi/jcabi-aspects#258]
I came to know about @Loggable annotation of [jcabi](http://aspects.jcabi.com/annotation-loggable.html) but am not successful in implementing that and your help is highly appreciated.

Below is the code that i have tried.

  ```
import com.jcabi.aspects.Loggable;
  import lombok.extern.slf4j.Slf4j;

  @Slf4j
  public class Jcabi {


  @Loggable
  private static String checkJcabi(String stringToPrint) {
     log.info("Print Successfull");
     return stringToPrint;
  }

  public static void main(String[] args) {
    checkJcabi("Hello World!");
  }

  }
```

IDE console prints this.

`[main] INFO com.amazon.optimus.cpamutil.utils.Jcabi - Print Successfull`

This is the log for the log.info i have added in the method and there is no log for the @loggable annotation something like this(below) as mentioned in this [post](http://www.yegor256.com/2014/06/01/aop-aspectj-java-method-logging.html)

`[INFO] com.example.Foo #power(2, 10): 1024 in 12μs
[INFO] com.example.Foo #power(3, 3): 27 in 4μs`

Below are the dependencies packages that i use.

JCabiAspects = 1.0;

AspectJ = 6.0;

Slf4j = 1.7;

Slf4j_Simple = 1.7;

Let me know if you need more details. Thanks.

I have also posted this same question in [stackoverflow](https://stackoverflow.com/questions/48647825/aspects-jcabi-loggable-doesnt-add-logs-to-the-output).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by santhosh12992** [comment]
@0crat 
@yegor256 

I am struck on this for a while and your help is highly appreciated.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/jcabi/jcabi-aspects/issues/258#issuecomment-363989381). You must always start your message with my name if you want to address it to me, see [§1](http://datum.zerocracy.com/pages/policy.html#1).

**Comment by yegor256** [comment]
@santhosh12992 you need to weave your binaries: http://plugin.jcabi.com/example-ajc.html

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-aspects#258` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#258](https://github.com/jcabi/jcabi-aspects/issues/258) was not in scope

**Comment by santhosh12992** [comment]
@yegor256  Thanks for the response.

I am using a stand alone java application. 

How i can use jcabi-maven-plugin there?

You help is really appreciated.

**Comment by yegor256** [comment]
@santhosh12992 start to use Maven. No matter what application you are developing, you need a builder. Stop using IDEs for that. Build your products from command line, using Maven.
