### ISSUE TITLE
How to install jcabi-aspects?

### ISSUE THREAD

**Issue by schittli** [jcabi/jcabi-aspects#261]
Good morning
**thank you very much** for jcabi-aspects, it looks great and very useful.

It's a pity that you put so much valuable work into this framework and the concrete installation remains a mystery in  README.md / on the website [Useful Java AOP Aspects](https://aspects.jcabi.com/) 

#### For newcomers like me, those are some basic questions:

1. Am I right in assuming that the first step is to set up [Eclipse AspectJ]?(https://www.eclipse.org/aspectj/)
2. I expected that your build process creates something like a jcabi-aspects.jar file.
But there is no jar file and the website [Useful Java AOP Aspects](https://aspects.jcabi.com/) explains, that this is enough: 
_If you want to use a current version of the product, you can do it with this configuration in your pom.xml_
» Will the modified pom.xml automatically download jcabi-aspects Framework?
3. I never used maven and it looks like pom.xml is used to configure maven.
Am I right in assuming that jcabi-aspects relates on maven as a best practice?
4. Of course, if I add `@Loggable(Loggable.DEBUG)` to a method, the IntelliJ community edition reports the error: `cannot resolve the Symbol 'Loggable'`.
I guess that I have to reference a jcabi-aspects.jar file… but as asked in Q2, there is no jcabi-aspects.jar file.

I'm very sorry to ask such basic questions, but I already have spent more than 3 hours to try to get started :-(

btw. for other newcomers: In the IntelliJ Community Edition, it's no problem to install the Plugin AspectJ weaver, but I guess that it's just a wrapper to call the right post-build process and one still needs to install all AspectJ and jcabi-aspects.

Thanks a lot for any light!
kind regards,
Thomas

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@schittli[/z](https://www.0crat.com/u/schittli) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by schittli** [comment]
@0crat thank you for your answers!, 
yes, I hate the situation that _many big commercial products use libraries like this and do not offer any penny_. 
At work, I tried to get 500US$ to support Open Source Project - without success: they're not willing to give any penny from the many 100000$ profits :-( :-[

It's even worse: Microsoft sells very expensive products, we pay for them and have to test them ourselves for some time now. Some time ago I reported a bug. Microsoft's answer: please fix it in github and send the fix. That's a great concept: let the customers pay the products - and let them do the work for testing and fixing.

That's the reason why I strictly stopped to support commercial 'open source' products.

#### For jcabi-aspects I propose
to use this great Idea: [GitHub Sponsors](https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/)

In this year, I spend almost 1000 working hours for developing software for nonprofit organizations, 
therefore, I'm very sorry that I can't financially support jcabi-aspects.
But at least I contributed a list of questions to make it easier for new users to get started - and they are all potential donors :-)

Hopefully.

**Comment by 0crat** [comment]
> @0crat thank you for your answers!, yes, I hate the situation that _many big commercial product... ([here](https://github.com/jcabi/jcabi-aspects/issues/261#issuecomment-512765794))

@schittli Can't understand "thank", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by yegor256** [comment]
@schittli would be better if you ask these questions on StackOverlow and label them with `jcabi` tag. This issue tracking is for problem solving, not helping users.

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-aspects#261` is not assigned, can't get performer

**Comment by schittli** [comment]
@yegor256 thank you for your feedback!, 
I think it's an issue because you have spent thousands of hours into this project and stopped one or two hours before reaching the target.

That's why it's a pity for your great work if interested users can not just start but they must spend hours to try to get started if a short Step by Step introduction would make them enthusiastic and not frustrated new users who carry this framework out into the world :-)

Of course, StackOverflow can help - but I guess they should not be misused to replace basic Docs ;-)

**Comment by yegor256** [comment]
@schittli I wrote this blog post https://www.yegor256.com/2014/06/01/aop-aspectj-java-method-logging.html to explain how things work. If you need more information and help, I'm ready to teach/train you for $200/hour :)
