### ISSUE TITLE
Annotation @Timeable doesn't work

### ISSUE THREAD

**Issue by YuriHagel** [jcabi/jcabi-aspects#263]
Hello!
Annotation @Timeable doesn't work
public class Test {
    public static void main(String[] args) {
        slow();
    }

    @Timeable(limit = 1, unit = TimeUnit.MILLISECONDS)
    public static void slow() {
        try {
            TimeUnit.SECONDS.sleep(3);
            System.out.println("ereetreter");
        } catch (InterruptedException e) {
            e.printStackTrace();
            throw new IllegalArgumentException("Query timeout in stored procedure");
        }
    }
}

<dependency>
            <groupId>com.jcabi</groupId>
            <artifactId>jcabi-aspects</artifactId>
            <version>0.22.6</version>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
            <version>1.6.12</version>
            <scope>runtime</scope>
        </dependency>
    <dependency>

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@yurihagel[/z](https://www.0crat.com/u/yurihagel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by gbham** [comment]
any progress?

**Comment by yegor256** [comment]
@YuriHagel how exactly it doesn't work? Also, did you do the weaving?  Read this: https://www.yegor256.com/2014/06/01/aop-aspectj-java-method-logging.html

**Comment by gbham** [comment]
@yegor256 I used this article: https://aspects.jcabi.com/example-weaving.html

I done as instructed but function just ignores the Timeable and continues as normal.

**Comment by yegor256** [comment]
@YuriHagel this means only one thing -- weaving doesn't work

**Comment by gbham** [comment]
@yegor256 So you are saying there is nothing wrong with @Timeable?

**Comment by yegor256** [comment]
@YuriHagel it is used in many projects for many years. It does work :)

**Comment by gbham** [comment]
@yegor256 To claim it works in every environment when there are 2 open issues seems a bit premature to me. I will take a closer look at the weaving then.

**Comment by andreoss** [comment]
Closing in favor of #249
