### ISSUE TITLE
Can't build jcabi-aspects myself

### ISSUE THREAD

**Issue by Mechtilde** [jcabi/jcabi-aspects#265]
When I build jcabi-aspects myself I got the message 
"package com.jcabi.aspects.version does not exist"

I looked under 
https://repo1.maven.org/maven2/com/jcabi/jcabi-aspects/0.22.6/jcabi-aspects-0.22.6-sources.jar
into the source file. there I found a directory "version" beside "aj" and  "apt".

So I think here in the source code that directory is missing.

Kind regards

**Comment by andreoss** [comment]
@Mechtilde Were you trying to build it from sources jar? That's not what sources-jars for.

**Comment by Mechtilde** [comment]
I tried to build from these sources:
https://github.com/jcabi/jcabi-aspects/archive/0.22.3.tar.gz and get the message that "package com.jcabi.aspects.version does not exist".

And why this part is in the source archive i cite I guess that it is missing here.

If there is another place where I can get the source code to build it successfully please give me a hint.

Kind regards

**Comment by andreoss** [comment]
@Mechtilde Besides one failing tests, this version compiles and builds just fine. 
Can you attach a build log? 

```
$ wget https://github.com/jcabi/jcabi-aspects/archive/0.22.3.tar.gz -O- | tar xzf - 
$ cd jcabi-aspects-0.22.3/
$ mvn install -DskipTests
```

**Comment by andreoss** [comment]
@Mechtilde Closing for now, feel free to open new issue if the problem persists
