### ISSUE TITLE
How to customize the log output when use @ Loggable?

### ISSUE THREAD

**Issue by finalcreator** [jcabi/jcabi-aspects#324]
How to customize the log output when use @ Loggable?

The doc said:

public class Resource {
  @Loggable(Loggable.DEBUG)
  public String load(URL url) {
    return url.openConnection().getContent();
  }
}

[DEBUG] #load('http://www.google.com'): returned "<html ..." in 23ms

**Comment by andreoss** [comment]
Javadoc has all available for customization options:
https://javadoc.io/static/com.jcabi/jcabi-aspects/0.24.1/com/jcabi/aspects/Loggable.html

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-aspects#324` is not assigned, can't get performer

**Comment by finalcreator** [comment]
I mean change string template :)

**Comment by finalcreator** [comment]
or add more code at pre and post

**Comment by andreoss** [comment]
I'm afraid it's impossible, that string is being generated at runtime, not by some template. 

https://github.com/jcabi/jcabi-aspects/blob/master/src/main/java/com/jcabi/aspects/aj/Mnemos.java#L143
