### ISSUE TITLE
ImmutableTest.java:57-58: The test is disabled since...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aspects#33]
Puzzle `133-94684a15` in `src/test/java/com/jcabi/aspects/ImmutableTest.java:57-58` has to be resolved: The test is disabled since in Java final arrays can still be modified (bloody Java!)

**Comment by 0pdd** [comment]
@dmarkov this puzzle is still not solved: [242](https://github.com/jcabi/jcabi-aspects/issues/242)

**Comment by 0pdd** [comment]
@dmarkov the puzzle [#unknown]() is still not solved.
