### ISSUE TITLE
Making logger loading of @Loggable annotation more flexible

### ISSUE THREAD

**Issue by ignatiomobius** [jcabi/jcabi-aspects#85]
As far as I understand it, @Loggabble currently uses com.jcabi.log.Logger which in turn calls org.slf4j.LoggerFactory#LoggerFactory.getLogger([Class-that-uses-the-annotation].class) to get a logger.

In my project (using logback), I would like to get a logger by String (so I can load a custom logger for some classes).

Proposal:  Extend @Loggable with another parameter  "loggername" which, if set, causes jcabi-Logger to use getLogger(String name) instead of getLogger(Class clazz)

**Comment by dmarkov** [comment]
the last puzzle `85-4b96ddcb`/#107 originated from here solved
