### ISSUE TITLE
Define member variables to add to log payload

### ISSUE THREAD

**Issue by xerofun** [jcabi/jcabi-aspects#87]
I have a handful of methods that I'd like to track that are essentially "process()" methods.  This stems from the fact that they are runnables and are parameterized at instantiation.  I'd like to be able to instruct the annotation to also print out one of the member variables as though it were a parameter.

```
private final Path file;

@Loggable(additionalParameters = {"file", "id"})
private void process()
{...}
```

**Comment by dmarkov** [comment]
the last puzzle `87-2655d0cc`/#111 solved
